github: # [user1, user2, ...]
patreon: # username
open_collective: # username
ko_fi: # username
tidelift: # platform-name/package-name
community_bridge: # project-name
liberapay: # username
issuehunt: # username
otechie: # username
custom: # ['link1', 'link2', ...]
